version: "1.0"

services:
  app:
    container_name: "azullia"
    build: ./
    ports:
      - "8080:80"

    networks:
      - AzuLLia

  mongo:
    container_name: "mongoDB"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - AzuLLia

networks:
  AzuLLia:
    external: false


