basePath: /
definitions:
  service.GeneralJSONHeader:
    properties:
      code:
        type: integer
      data:
        additionalProperties: true
        type: object
      msg:
        type: string
      path:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: 一只轻量级无头CMS
  title: AzuLLia
  version: 1.0.1206
paths:
  /about:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取框架版本信息
      tags:
      - 系统
  /api/articleList:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取列表
      tags:
      - 文章
  /api/categoryList:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取分类列表
      tags:
      - 分类
  /api/tagList:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取标签列表
      tags:
      - 标签
  /data/article/{id}:
    get:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取文章内容
      tags:
      - 文章
  /data/category/{id}:
    get:
      parameters:
      - description: 分类ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取分类
      tags:
      - 分类
  /data/tag/{id}:
    get:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取标签
      tags:
      - 标签
swagger: "2.0"
