basePath: /
definitions:
  service.GeneralJSONHeader:
    properties:
      code:
        type: integer
      data:
        additionalProperties: true
        type: object
      msg:
        type: string
      path:
        type: string
    type: object
  service.articleTable:
    properties:
      allowComment:
        description: 是否允许评论
        type: boolean
      authorId:
        description: 内容所属用户
        type: string
      created:
        description: 内容生成时的时间戳
        type: integer
      id:
        description: 主键，自增
        type: string
      modified:
        description: 内容修改时的时间戳
        type: integer
      order:
        description: 排序
        type: integer
      password:
        description: 受保护内容的密码
        type: string
      slug:
        description: 内容缩略名
        type: string
      status:
        description: 内容状态
        type: string
      template:
        description: 内容所使用的模版
        type: string
      text:
        description: 内容文字
        type: string
      title:
        description: 内容标题
        type: string
      type:
        description: 内容类别
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: 一只轻量级无头CMS
  title: AzuLLia
  version: 1.0.1206
paths:
  /about:
    get:
      description: 获取框架版本信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取框架版本信息
      tags:
      - 系统
  /api/v1/article:
    delete:
      description: 删除指定id文章(需要相关权限token)
      parameters:
      - description: 文章id
        in: formData
        name: id
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 删除文章
      tags:
      - 文章
    get:
      description: 获取全部文章列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取列表
      tags:
      - 文章
    post:
      description: 添加新文章(需要相关权限token)
      parameters:
      - description: JSON数据
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/service.articleTable'
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 添加文章
      tags:
      - 文章
    put:
      description: 更新指定id文章(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 缩略名
        in: formData
        name: slug
        required: true
        type: string
      - description: 分类
        in: formData
        name: type
        required: true
        type: string
      - description: 描述
        in: formData
        name: description
        required: true
        type: string
      - description: 排序
        in: formData
        name: order
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 更新文章
      tags:
      - 文章
  /api/v1/article/{id}:
    get:
      description: 获取指定id文章列表
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取文章内容
      tags:
      - 文章
  /api/v1/auth/refresh:
    post:
      description: 当refresh_token失效时请求，需要传入过期的refresh_token，如通过校验则返回新的refresh_token
      parameters:
      - description: Refresh_Token
        in: formData
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 身份认证获取
      tags:
      - Token
  /api/v1/auth/signin:
    post:
      description: 使用账户名和密码进行登录并返回token和refresh_token，其中token每两小过期，需要refresh_token获取新的token，refresh_token每一周过期
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: passwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 用户登陆
      tags:
      - Token
  /api/v1/category:
    delete:
      description: 删除指定id分类(需要相关权限token)
      parameters:
      - description: 分类id
        in: formData
        name: id
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 删除分类
      tags:
      - 分类
    get:
      description: 获取全部分类列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取分类列表
      tags:
      - 分类
    post:
      description: 添加新分类(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 缩略名
        in: formData
        name: slug
        required: true
        type: string
      - description: 描述
        in: formData
        name: description
        required: true
        type: string
      - description: 排序
        in: formData
        name: order
        required: true
        type: integer
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 添加分类
      tags:
      - 分类
    put:
      description: 更新指定id分类(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 缩略名
        in: formData
        name: slug
        required: true
        type: string
      - description: 选项描述
        in: formData
        name: description
        required: true
        type: string
      - description: 项目个数
        in: formData
        name: count
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 更新分类
      tags:
      - 分类
  /api/v1/category/{id}:
    get:
      description: 获取指定id分类列表
      parameters:
      - description: 分类ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取分类
      tags:
      - 分类
  /api/v1/group:
    delete:
      description: 删除指定id分类(需要相关权限token)
      parameters:
      - description: 用户组id
        in: formData
        name: id
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 删除用户组
      tags:
      - 用户组
    post:
      description: 添加新用户组(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 排序
        in: formData
        name: order
        required: true
        type: integer
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 添加用户组
      tags:
      - 用户组
    put:
      description: 更新指定id用户组(需要相关权限token)
      parameters:
      - description: ID
        in: formData
        name: id
        required: true
        type: string
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 更新用户组
      tags:
      - 用户组
  /api/v1/tag:
    delete:
      description: 删除指定id标签(需要相关权限token)
      parameters:
      - description: 标签id
        in: formData
        name: id
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 删除标签
      tags:
      - 标签
    get:
      description: 获取全部标签列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取标签列表
      tags:
      - 标签
    post:
      description: 添加新标签(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 缩略名
        in: formData
        name: slug
        required: true
        type: string
      - description: 类型
        in: formData
        name: type
        required: true
        type: string
      - description: 描述
        in: formData
        name: description
        required: true
        type: string
      - description: 排序
        in: formData
        name: order
        required: true
        type: integer
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 添加标签
      tags:
      - 标签
    put:
      description: 更新指定id标签(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 缩略名
        in: formData
        name: slug
        required: true
        type: string
      - description: 分类
        in: formData
        name: type
        required: true
        type: string
      - description: 描述
        in: formData
        name: description
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 更新标签
      tags:
      - 标签
  /api/v1/tag/{id}:
    get:
      description: 获取全部标签列表
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 获取标签
      tags:
      - 标签
  /api/v1/user:
    delete:
      description: 删除指定id用户(需要相关权限token)
      parameters:
      - description: 用户id
        in: formData
        name: id
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 删除用户
      tags:
      - 用户
    get:
      description: 获取全部用户列表(需要相关权限token)
      parameters:
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 用户列表
      tags:
      - 用户
    post:
      description: 添加新用户(需要相关权限token)
      parameters:
      - description: 名称
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: passwd
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: mail
        required: true
        type: string
      - description: 网站地址
        in: formData
        name: url
        required: true
        type: string
      - description: 用户昵称
        in: formData
        name: screenName
        required: true
        type: string
      - description: 用户组
        in: formData
        name: group
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 添加用户
      tags:
      - 用户
    put:
      description: 更新指定id用户(需要相关权限token)
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: passwd
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: mail
        required: true
        type: string
      - description: 网址
        in: formData
        name: url
        required: true
        type: string
      - description: 昵称
        in: formData
        name: screenName
        required: true
        type: string
      - description: 用户组
        in: formData
        name: group
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 更新用户
      tags:
      - 用户
  /test/123:
    get:
      description: 这是一个测试函数，用于在开发模式中测试各种功能(发行版模式下会失效)
      parameters:
      - description: 文章id
        in: formData
        name: id
        type: string
      - description: token
        in: header
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GeneralJSONHeader'
      summary: 测试函数
      tags:
      - 测试
swagger: "2.0"
